# Generated by Django 2.2.6 on 2019-12-07 11:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='community_thumbnail/no-img.jpg', upload_to='community_thumbnail')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('post_data', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='komunitipage.Community')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('is_required', models.BooleanField(db_index=True, default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='komunitipage.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_desc', models.CharField(max_length=100)),
                ('tag_info', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='komunitipage.Community')),
            ],
        ),
    ]
