# Generated by Django 2.2.6 on 2019-12-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komunitipage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='data_fields',
            new_name='data_field',
        ),
    ]
