# Generated by Django 2.2.6 on 2019-12-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komunitipage', '0004_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='upload',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
