# Generated by Django 2.2.6 on 2019-12-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komunitipage', '0005_auto_20191217_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityTag',
        ),
    ]
