# Generated by Django 2.2.6 on 2019-12-21 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komunitipage', '0008_auto_20191221_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KomunitiUser',
            new_name='User',
        ),
    ]
